#!/bin/bash

# Generate expanded UK location wordlist for pentest: CountryYear, CountyYear, CityYear, TownYear, BoroughYear
# Expanded to include comprehensive lists: ~76 cities, ~200 towns (largest, some overlap with cities), ~150 counties, ~168 boroughs/districts
# Locations start with uppercase first character
# Years: last 10 years including current year
# Special chars: common ones based on password analyses (! @ # $ %)
# Prefixes/Suffixes: empty + all combinations of 1-3 length from specials
# Outputs: prefix + base + suffix for each base word, saved to uk_passwords.txt
# Sources: Wikipedia, CityPopulation.de for expanded data (title case, UTF-8 if needed)
# Multi-threaded: Uses GNU Parallel for parallel generation (one thread per base, auto-detects cores)

# Define UK countries (unchanged)
countries=(
    England
    Scotland
    Wales
    "Northern Ireland"
)

# Expanded counties (~150 from Wikipedia ceremonial/administrative/historic)
counties=(
    "Avon"
    "Bath And North East Somerset"
    "Bedfordshire"
    "Bedford"
    "Berkshire"
    "Blackburn With Darwen"
    "Blackpool"
    "Bournemouth, Christchurch And Poole"
    "Bournemouth"
    "Brighton And Hove"
    "Bristol"
    "Buckinghamshire"
    "Cambridgeshire"
    "Cambridgeshire And Isle Of Ely"
    "Central Bedfordshire"
    "Cheshire"
    "Cheshire East"
    "Cheshire West And Chester"
    "Cleveland"
    "Cornwall"
    "Cumberland"
    "Cumbria"
    "Darlington"
    "Derbyshire"
    "Derby"
    "Devon"
    "Dorset"
    "Durham"
    "East Suffolk"
    "East Sussex"
    "Essex"
    "Gloucestershire"
    "Greater London"
    "Greater Manchester"
    "Hampshire"
    "Halton"
    "Hartlepool"
    "Hereford And Worcester"
    "Herefordshire"
    "Hertfordshire"
    "Humberside"
    "Huntingdon And Peterborough"
    "Huntingdonshire"
    "Isle Of Ely"
    "Isle Of Wight"
    "Kent"
    "Kingston Upon Hull"
    "Lancashire"
    "Leicestershire"
    "Leicester"
    "Lincolnshire"
    "London"
    "City Of London"
    "Luton"
    "Medway"
    "Merseyside"
    "Middlesbrough"
    "Middlesex"
    "Milton Keynes"
    "Norfolk"
    "Northamptonshire"
    "North East Lincolnshire"
    "North Humberside"
    "North Lincolnshire"
    "North Northamptonshire"
    "North Somerset"
    "Northumberland"
    "North Yorkshire"
    "Nottinghamshire"
    "Nottingham"
    "Oxfordshire"
    "Soke Of Peterborough"
    "Peterborough"
    "Plymouth"
    "Poole"
    "Portsmouth"
    "Redcar And Cleveland"
    "Rutland"
    "Shropshire"
    "Somerset"
    "Southampton"
    "Southend-On-Sea"
    "South Humberside"
    "South Gloucestershire"
    "South Yorkshire"
    "Staffordshire"
    "Stockton-On-Tees"
    "Stoke-On-Trent"
    "Suffolk"
    "Surrey"
    "Sussex"
    "Swindon"
    "Telford And Wrekin"
    "Thurrock"
    "Torbay"
    "Tyne And Wear"
    "Warrington"
    "Warwickshire"
    "West Midlands"
    "Westmorland"
    "Westmorland And Furness"
    "West Northamptonshire"
    "West Suffolk"
    "West Sussex"
    "West Yorkshire"
    "Wiltshire"
    "Worcestershire"
    "Yorkshire"
    "East Riding Of Yorkshire"
    "North Riding Of Yorkshire"
    "West Riding Of Yorkshire"
    "York"
    "Antrim"
    "Armagh"
    "Belfast"
    "Down"
    "Fermanagh"
    "Londonderry"
    "Derry"
    "Tyrone"
    "Aberdeen"
    "Aberdeenshire"
    "Angus"
    "Argyll"
    "Ayrshire"
    "Banffshire"
    "Berwickshire"
    "Bute"
    "Caithness"
    "Clackmannanshire"
    "Cromartyshire"
    "Dumfriesshire"
    "Dunbartonshire"
    "Dundee"
    "East Lothian"
    "Edinburgh"
    "Fife"
    "Glasgow"
    "Inverness-Shire"
    "Kincardineshire"
    "Kinross-Shire"
    "Kirkcudbrightshire"
    "Lanarkshire"
    "Midlothian"
    "Moray"
    "Nairnshire"
    "Orkney"
    "Peeblesshire"
    "Perthshire"
    "Renfrewshire"
    "Ross And Cromarty"
    "Ross-Shire"
    "Roxburghshire"
    "Selkirkshire"
    "Shetland"
    "Stirlingshire"
    "Sutherland"
    "West Lothian"
    "Wigtownshire"
    "Anglesey"
    "Brecknockshire"
    "Caernarfonshire"
    "Cardiganshire"
    "Carmarthenshire"
    "Clwyd"
    "Denbighshire"
    "Dyfed"
    "Flintshire"
    "Glamorgan"
    "Gwent"
    "Gwynedd"
    "Merionethshire"
    "Mid Glamorgan"
    "Monmouthshire"
    "Montgomeryshire"
    "Pembrokeshire"
    "Powys"
    "Radnorshire"
    "South Glamorgan"
    "West Glamorgan"
    "Wrexham"
)

# Expanded cities (~76 from Wikipedia)
cities=(
    "London"
    "Westminster"
    "Birmingham"
    "Leeds"
    "Glasgow"
    "Manchester"
    "Sheffield"
    "Bradford"
    "Edinburgh"
    "Liverpool"
    "Bristol"
    "Cardiff"
    "Leicester"
    "Coventry"
    "Wakefield"
    "Belfast"
    "Nottingham"
    "Newcastle upon Tyne"
    "Doncaster"
    "Milton Keynes"
    "Salford"
    "Sunderland"
    "Brighton and Hove"
    "Wolverhampton"
    "Kingston upon Hull"
    "Plymouth"
    "Derby"
    "Stoke-on-Trent"
    "Southampton"
    "Swansea"
    "Aberdeen"
    "Peterborough"
    "Portsmouth"
    "York"
    "Colchester"
    "Chelmsford"
    "Southend-on-Sea"
    "Oxford"
    "Newport"
    "Canterbury"
    "Preston"
    "Dundee"
    "Cambridge"
    "St Albans"
    "Lancaster"
    "Norwich"
    "Chester"
    "Exeter"
    "Wrexham"
    "Gloucester"
    "Winchester"
    "Durham"
    "Carlisle"
    "Worcester"
    "Lincoln"
    "Bath"
    "Derry"
    "Dunfermline"
    "Bangor"
    "Inverness"
    "Hereford"
    "Lisburn"
    "Stirling"
    "Perth"
    "Salisbury"
    "Lichfield"
    "Chichester"
    "Newry"
    "Truro"
    "Ely"
    "Ripon"
    "Armagh"
    "Bangor"
    "Wells"
    "St Asaph"
    "St Davids"
)

# Expanded towns (~200 largest from CityPopulation.de, including some smaller cities for comprehensiveness; overlaps possible)
towns=(
    "Aberdeen"
    "Ashford"
    "Aylesbury"
    "Banbury"
    "Bangor"
    "Barnsley"
    "Barrow-in-Furness"
    "Barry"
    "Basildon"
    "Basingstoke"
    "Bath"
    "Bebington"
    "Bedford"
    "Beeston"
    "Birkenhead"
    "Blackburn"
    "Blackpool"
    "Bloxwich"
    "Bognor Regis"
    "Bolton"
    "Bootle"
    "Bournemouth"
    "Bracknell"
    "Bradford"
    "Brentwood"
    "Bridgend"
    "Brighton and Hove"
    "Bristol"
    "Burnley"
    "Burton upon Trent"
    "Bury"
    "Cambridge"
    "Cannock"
    "Canterbury"
    "Cardiff"
    "Carlisle"
    "Carlton"
    "Chatham"
    "Chelmsford"
    "Cheltenham"
    "Chester"
    "Chesterfield"
    "Clacton-on-Sea"
    "Colchester"
    "Corby"
    "Coventry"
    "Craigavon"
    "Crawley"
    "Crewe"
    "Crosby"
    "Cumbernauld"
    "Darlington"
    "Dartford"
    "Derby"
    "Derry"
    "Dewsbury"
    "Doncaster"
    "Dudley"
    "Dundee"
    "Dunfermline"
    "Durham"
    "Eastbourne"
    "East Kilbride"
    "Ellesmere Port"
    "Esher"
    "Exeter"
    "Farnborough"
    "Folkestone"
    "Gateshead"
    "Gillingham"
    "Gloucester"
    "Gosport"
    "Gravesend"
    "Grimsby"
    "Guildford"
    "Halesowen"
    "Halifax"
    "Hamilton"
    "Harlow"
    "Harrogate"
    "Hartlepool"
    "Hastings"
    "Hemel Hempstead"
    "Hereford"
    "High Wycombe"
    "Hinckley"
    "Horsham"
    "Huddersfield"
    "Huyton with Roby"
    "Ipswich"
    "Kettering"
    "Kidderminster"
    "Kingston upon Hull"
    "Kingswinford"
    "Kingswood"
    "Kirkcaldy"
    "Lancaster"
    "Leeds"
    "Leicester"
    "Lincoln"
    "Lisburn"
    "Liverpool"
    "Livingston"
    "Loughborough"
    "Lowestoft"
    "Luton"
    "Macclesfield"
    "Maidenhead"
    "Maidstone"
    "Manchester"
    "Mansfield"
    "Margate"
    "Middlesbrough"
    "Milton Keynes"
    "Newcastle upon Tyne"
    "Newcastle-under-Lyme"
    "Newport"
    "Northampton"
    "Norwich"
    "Nottingham"
    "Nuneaton"
    "Oldham"
    "Oxford"
    "Paignton"
    "Paisley"
    "Peterborough"
    "Plymouth"
    "Poole"
    "Portsmouth"
    "Preston"
    "Reading"
    "Redditch"
    "Rochdale"
    "Rochester"
    "Rotherham"
    "Royal Leamington Spa"
    "Royal Sutton Coldfield"
    "Royal Tunbridge Wells"
    "Rugby"
    "Runcorn"
    "Sale"
    "Salford"
    "Scarborough"
    "Scunthorpe"
    "Sheffield"
    "Shrewsbury"
    "Sittingbourne"
    "Slough"
    "Smethwick"
    "Solihull"
    "Southampton"
    "Southend-on-Sea"
    "Southport"
    "South Shields"
    "Stafford"
    "St Albans"
    "Stevenage"
    "St Helens"
    "Stockport"
    "Stockton-on-Tees"
    "Stoke-on-Trent"
    "Stourbridge"
    "Sunderland"
    "Swansea"
    "Swindon"
    "Tamworth"
    "Taunton"
    "Telford"
    "Thundersley"
    "Torquay"
    "Tynemouth"
    "Wakefield"
    "Wallasey"
    "Walsall"
    "Warrington"
    "Washington"
    "Watford"
    "Wellingborough"
    "Welwyn Garden City"
    "West Bromwich"
    "Weston-super-Mare"
    "Weymouth"
    "Widnes"
    "Wigan"
    "Woking"
    "Wokingham"
    "Wolverhampton"
    "Worcester"
    "Worthing"
    "Wythenshawe"
    "Yeovil"
    "York"
)

# Expanded boroughs/districts (~168 combined from London, metropolitan, non-metropolitan)
london_boroughs=(
    "City of Westminster"
    "Royal Borough of Kensington and Chelsea"
    "London Borough of Hammersmith and Fulham"
    "London Borough of Wandsworth"
    "London Borough of Lambeth"
    "London Borough of Southwark"
    "London Borough of Tower Hamlets"
    "London Borough of Hackney"
    "London Borough of Islington"
    "London Borough of Camden"
    "London Borough of Brent"
    "London Borough of Ealing"
    "London Borough of Hounslow"
    "London Borough of Richmond upon Thames"
    "Royal Borough of Kingston upon Thames"
    "London Borough of Merton"
    "London Borough of Sutton"
    "London Borough of Croydon"
    "London Borough of Bromley"
    "London Borough of Lewisham"
    "Royal Borough of Greenwich"
    "London Borough of Bexley"
    "London Borough of Havering"
    "London Borough of Barking and Dagenham"
    "London Borough of Redbridge"
    "London Borough of Newham"
    "London Borough of Waltham Forest"
    "London Borough of Haringey"
    "London Borough of Enfield"
    "London Borough of Barnet"
    "London Borough of Harrow"
    "London Borough of Hillingdon"
)

metropolitan_boroughs=(
    "Metropolitan Borough Of Liverpool"
    "Metropolitan Borough Of Knowsley"
    "Metropolitan Borough Of St Helens"
    "Metropolitan Borough Of Sefton"
    "Metropolitan Borough Of Wirral"
    "Metropolitan Borough Of Manchester"
    "Metropolitan Borough Of Bolton"
    "Metropolitan Borough Of Bury"
    "Metropolitan Borough Of Oldham"
    "Metropolitan Borough Of Rochdale"
    "City Of Salford"
    "Metropolitan Borough Of Stockport"
    "Tameside"
    "Trafford"
    "Metropolitan Borough Of Wigan"
    "City Of Sheffield"
    "Metropolitan Borough Of Barnsley"
    "Metropolitan Borough Of Doncaster"
    "Metropolitan Borough Of Rotherham"
    "City Of Newcastle Upon Tyne"
    "Metropolitan Borough Of Gateshead"
    "South Tyneside"
    "North Tyneside"
    "City Of Sunderland"
    "Birmingham"
    "City Of Coventry"
    "Metropolitan Borough Of Dudley"
    "Sandwell"
    "Metropolitan Borough Of Solihull"
    "Metropolitan Borough Of Walsall"
    "City Of Wolverhampton"
    "City Of Leeds"
    "City Of Bradford"
    "Calderdale"
    "Kirklees"
    "City Of Wakefield"
)

other_boroughs=(
    "Cambridge"
    "South Cambridgeshire"
    "Huntingdonshire"
    "Fenland"
    "East Cambridgeshire"
    "High Peak"
    "Derbyshire Dales"
    "South Derbyshire"
    "Erewash"
    "Amber Valley"
    "North East Derbyshire"
    "Chesterfield"
    "Bolsover"
    "Exeter"
    "East Devon"
    "Mid Devon"
    "North Devon"
    "Torridge"
    "West Devon"
    "South Hams"
    "Teignbridge"
    "Hastings"
    "Rother"
    "Wealden"
    "Eastbourne"
    "Lewes"
    "Harlow"
    "Epping Forest"
    "Brentwood"
    "Basildon"
    "Castle Point"
    "Rochford"
    "Maldon"
    "Chelmsford"
    "Uttlesford"
    "Braintree"
    "Colchester"
    "Tendring"
    "Gloucester"
    "Tewkesbury"
    "Cheltenham"
    "Cotswold"
    "Stroud"
    "Forest of Dean"
    "Gosport"
    "Fareham"
    "Winchester"
    "Havant"
    "East Hampshire"
    "Hart"
    "Rushmoor"
    "Basingstoke and Deane"
    "Test Valley"
    "Eastleigh"
    "New Forest"
    "Three Rivers"
    "Watford"
    "Hertsmere"
    "Welwyn Hatfield"
    "Broxbourne"
    "East Hertfordshire"
    "Stevenage"
    "North Hertfordshire"
    "St Albans"
    "Dacorum"
    "Dartford"
    "Gravesham"
    "Sevenoaks"
    "Tonbridge and Malling"
    "Tunbridge Wells"
    "Maidstone"
    "Swale"
    "Ashford"
    "Folkestone and Hythe"
    "Canterbury"
    "Dover"
    "Thanet"
    "West Lancashire"
    "Chorley"
    "South Ribble"
    "Fylde"
    "Preston"
    "Wyre"
    "Lancaster"
    "Ribble Valley"
    "Pendle"
    "Burnley"
    "Rossendale"
    "Hyndburn"
    "Charnwood"
    "Melton"
    "Harborough"
    "Oadby and Wigston"
    "Blaby"
    "Hinckley and Bosworth"
    "North West Leicestershire"
    "Lincoln"
    "North Kesteven"
    "South Kesteven"
    "South Holland"
    "Boston"
    "East Lindsey"
    "West Lindsey"
    "Norwich"
    "South Norfolk"
    "Great Yarmouth"
    "Broadland"
    "North Norfolk"
    "King's Lynn and West Norfolk"
    "Breckland"
    "Rushcliffe"
    "Broxtowe"
    "Ashfield"
    "Gedling"
    "Newark and Sherwood"
    "Mansfield"
    "Bassetlaw"
    "Oxford"
    "Cherwell"
    "South Oxfordshire"
    "Vale of White Horse"
    "West Oxfordshire"
    "Tamworth"
    "Lichfield"
    "Cannock Chase"
    "South Staffordshire"
    "Stafford"
    "Newcastle-under-Lyme"
    "Staffordshire Moorlands"
    "East Staffordshire"
    "Ipswich"
    "Babergh"
    "East Suffolk"
    "Mid Suffolk"
    "West Suffolk"
    "Spelthorne"
    "Runnymede"
    "Surrey Heath"
    "Woking"
    "Elmbridge"
    "Guildford"
    "Waverley"
    "Mole Valley"
    "Epsom and Ewell"
    "Reigate and Banstead"
    "Tandridge"
    "North Warwickshire"
    "Nuneaton and Bedworth"
    "Rugby"
    "Stratford-on-Avon"
    "Warwick"
    "Worthing"
    "Arun"
    "Chichester"
    "Horsham"
    "Crawley"
    "Mid Sussex"
    "Adur"
    "Worcester"
    "Malvern Hills"
    "Wyre Forest"
    "Bromsgrove"
    "Redditch"
    "Wychavon"
)

# Combine boroughs into one array
boroughs=("${london_boroughs[@]}" "${metropolitan_boroughs[@]}" "${other_boroughs[@]}")

# Function to generate all combinations of given length from special_chars
generate_combos() {
    local length=$1
    local special_chars=( '!' '@' '#' '$' '%' )  # Define here for safety
    if [ $length -eq 1 ]; then
        for char in "${special_chars[@]}"; do
            echo "$char"
        done
    elif [ $length -eq 2 ]; then
        for char1 in "${special_chars[@]}"; do
            for char2 in "${special_chars[@]}"; do
                echo "${char1}${char2}"
            done
        done
    elif [ $length -eq 3 ]; then
        for char1 in "${special_chars[@]}"; do
            for char2 in "${special_chars[@]}"; do
                for char3 in "${special_chars[@]}"; do
                    echo "${char1}${char2}${char3}"
                done
            done
        done
    fi
}

# Get current year and calculate start year (10 years back)
current_year=$(date +%Y)
start_year=$((current_year - 9))

# Generate bases first
bases=()
for year in $(seq $start_year $current_year); do
    # Countries
    for country in "${countries[@]}"; do
        bases+=("${country}${year}")
    done
    # Counties
    for county in "${counties[@]}"; do
        bases+=("${county}${year}")
    done
    # Cities
    for city in "${cities[@]}"; do
        bases+=("${city}${year}")
    done
    # Towns
    for town in "${towns[@]}"; do
        bases+=("${town}${year}")
    done
    # Boroughs
    for borough in "${boroughs[@]}"; do
        bases+=("${borough}${year}")
    done
done

# Function to generate combinations for a single base (used by parallel)
# Regenerates everything locally in each thread (fast, small loops)
generate_for_base() {
    local base="$1"
    # Local definition of special_chars
    local special_chars=( '!' '@' '#' '$' '%' )
    # Local generation of prefixes/suffixes
    local prefixes=("")
    for len in 1 2 3; do
        while IFS= read -r combo; do
            prefixes+=("$combo")
        done < <(generate_combos $len)
    done
    local suffixes=("${prefixes[@]}")
    # Generate output
    for prefix in "${prefixes[@]}"; do
        for suffix in "${suffixes[@]}"; do
            echo "${prefix}${base}${suffix}"
        done
    done
}

# Export functions for parallel subshells
export -f generate_for_base
export -f generate_combos

# Prepare output file: overwrite if exists
rm -f uk_passwords.txt

# Multi-threaded generation using GNU Parallel (defaults to nproc threads)
num_bases=${#bases[@]}
printf "Generating %d expanded UK location bases in parallel (%d threads)...\n" "$num_bases" "$(nproc)" >&2
parallel -j$(nproc) --bar generate_for_base {} ::: "${bases[@]}" >> uk_passwords.txt
expected_entries=$(( num_bases * 156 * 156 ))
printf "\nDone. Saved to uk_passwords.txt (%d expected entries)\n" "$expected_entries" >&2

# Quick verification
if [ -f uk_passwords.txt ] && [ -s uk_passwords.txt ]; then
    entry_count=$(wc -l < uk_passwords.txt)
    printf "Verified: %d entries generated.\n" "$entry_count" >&2
    # Specific check for example: London2025!
    if grep -qF "London2025!" uk_passwords.txt; then
        printf "Verified: London2025! present.\n" >&2
    else
        printf "Warning: London2025! missing—investigate further.\n" >&2
    fi
else
    printf "Error: uk_passwords.txt is empty or missing. Check GNU Parallel installation and permissions.\n" >&2
fi
